// examples/react/src/App.jsx
import { useState } from 'react';
import { sx } from '@cssxio/cssx';
import * as cssx from '@cssxio/cssx';

const styles = cssx.create({
  page: 'flex min-h-[100vh] items-center justify-center bg-slate-950 p-8 font-[var(--font-display)]',
  card: 'flex max-w-lg flex-col items-start gap-6 rounded-2xl bg-slate-900 p-8 text-slate-100 shadow-2xl',
  eyebrow: 'text-sm font-medium text-brand',
  title: 'text-[2.5rem] leading-[1.1] font-semibold',
  copy: 'text-slate-300',
  hint: 'text-sm text-slate-400',
});

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <main {...cssx.props(styles.page)}>
      <section {...cssx.props(styles.card)}>
        <span {...cssx.props(styles.eyebrow)}>Create React App</span>
        <h1 {...cssx.props(styles.title)}>CSSX through webpack</h1>
        <p {...cssx.props(styles.copy)}>
          This example adds the CSSX webpack adapter through the Create React App configuration override.
        </p>
        <button
          className={sx(
            'rounded-md bg-brand px-4 py-2 font-medium text-white hover:bg-cyan-700',
            count > 0 && 'scale-105',
          )}
          onClick={() => setCount((value) => value + 1)}
        >
          count is {count}
        </button>
        <p {...cssx.props(styles.hint)}>CSSX extracts static utilities and composes counter state at runtime.</p>
      </section>
    </main>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import * as cssx from '@cssxio/cssx';
import { sx } from '@cssxio/cssx';

const count = ref(0);
const styles = cssx.create({
  page: 'flex min-h-[100vh] flex-col items-center justify-center gap-6 bg-slate-950 p-8 text-center text-slate-100',
  title: 'text-3xl font-semibold',
  card: 'flex flex-col items-center gap-4 rounded-xl bg-white p-6 text-slate-950 shadow-xl',
});
const page = cssx.props(styles.page);
const title = cssx.props(styles.title);
const card = cssx.props(styles.card);
</script>

<template>
  <main :class="page.className">
    <h1 :class="title.className">Vue + CSSX</h1>
    <section :class="card.className">
      <p>CSSX compiles script setup styles and template <code>sx()</code> calls.</p>
      <button
        :class="sx('rounded-md bg-brand px-4 py-2 font-medium text-white hover:scale-105', count > 0 && 'ring-2')"
        @click="count += 1"
      >
        count is {{ count }}
      </button>
    </section>
  </main>
</template>
